import{a as v,S as b,i}from"./assets/vendor-851Qsuw-.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function e(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(r){if(r.ep)return;r.ep=!0;const o=e(r);fetch(r.href,o)}})();const E="48211039-b5a5e94b0d08467a34362de56",S="https://pixabay.com/api/";async function m(s,t=1,e="",n="",r="all"){const o={key:E,q:s,image_type:r,orientation:"horizontal",safesearch:!0,per_page:15,page:t};e&&(o.category=e),n&&(o.colors=n);try{const a=await v.get(S,{params:o,timeout:1e4});return a.data.hits.length?a.data:{hits:[],totalHits:0}}catch(a){throw console.error("Error fetching images:",a.message||a),new Error("Failed to fetch images.")}}const p=document.querySelector("#gallery");let q=new SimpleLightbox(".gallery a",{captionsData:"alt",captionDelay:250});function y(s){const t=s.map(e=>`
      <a href="${e.largeImageURL}" class="gallery-item">
        <img src="${e.webformatURL}" alt="${e.tags}" />
        <div class="info">
          <span><strong>Likes:</strong> ${e.likes}</span>
          <span><strong>Views:</strong> ${e.views}</span>
          <span><strong>Comments:</strong> ${e.comments}</span>
          <span><strong>Downloads:</strong> ${e.downloads}</span>
        </div>
      </a>
    `).join("");p.insertAdjacentHTML("beforeend",t),q.refresh()}function I(){p.innerHTML=""}function P(){window.scrollBy({top:400,behavior:"smooth"})}let c="",d=1;const u=29,f=document.getElementById("loader"),$=document.querySelector("#search-form"),g=document.querySelector("#load-more");document.querySelector(".gallery");let l=new Set;const L=new b(".gallery a",{scrollZoom:!1});document.addEventListener("touchstart",()=>{},{passive:!0});document.addEventListener("touchmove",()=>{},{passive:!0});function w(){f.innerHTML='<div class="spinner"></div>',f.style.display="block"}function h(){f.innerHTML="",f.style.display="none"}$.addEventListener("submit",async s=>{if(s.preventDefault(),c=document.querySelector("#search-input").value.trim(),!c){i.info({title:"Info",message:"Please enter a search query!"});return}I(),l.clear(),d=1,g.classList.add("hidden"),w();try{const t=await m(c,d,u);if(h(),!t.hits.length){i.warning({title:"Warning",message:"Nothing found! Try another search."});return}const e=t.hits.filter(n=>!l.has(n.id));e.forEach(n=>l.add(n.id)),y(e),L.refresh(),t.hits.length>=u&&g.classList.remove("hidden")}catch(t){console.error("Error loading images:",t),h(),i.error({title:"Error",message:"Something went wrong. Please try again."})}});g.addEventListener("click",async()=>{d+=1,w();try{const s=await m(c,d,u);h();const t=s.hits.filter(e=>!l.has(e.id));t.forEach(e=>l.add(e.id)),t.length&&(y(t),L.refresh(),P()),s.hits.length<u&&(g.classList.add("hidden"),i.warning({title:"Warning",message:"We're sorry, but you've reached the end of search results."}))}catch(s){console.error("Error loading more images:",s),h(),i.error({title:"Error",message:"Something went wrong. Please try again."})}});
//# sourceMappingURL=index.js.map
