import{a as p,S as w,i as l}from"./assets/vendor-851Qsuw-.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))e(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&e(n)}).observe(document,{childList:!0,subtree:!0});function a(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function e(r){if(r.ep)return;r.ep=!0;const o=a(r);fetch(r.href,o)}})();const L="48211039-b5a5e94b0d08467a34362de56",S="https://pixabay.com/api/";async function m(s,t=1,a="",e="",r="all"){const o={key:L,q:s,image_type:r,orientation:"horizontal",safesearch:!0,per_page:15,page:t};a&&(o.category=a),e&&(o.colors=e);try{const n=await p.get(S,{params:o});return n.data.hits.length===0&&toastr.warning("No images found for your query. Try something else."),n.data}catch(n){throw toastr.error("Something went wrong. Please try again."),console.error(n),new Error("Failed to fetch images.")}}function h(s){const t=document.querySelector("#gallery"),a=s.map(e=>`
      <a href="${e.largeImageURL}" class="gallery-item">
        <img src="${e.webformatURL}" alt="${e.tags}" />
        <div class="info">
          <span><strong>Likes:</strong> ${e.likes}</span>
          <span><strong>Views:</strong> ${e.views}</span>
          <span><strong>Comments:</strong> ${e.comments}</span>
          <span><strong>Downloads:</strong> ${e.downloads}</span>
        </div>
      </a>
    `).join("");t.insertAdjacentHTML("beforeend",a),new SimpleLightbox(".gallery-item",{captionsData:"alt",captionDelay:250})}function q(){document.querySelector("#gallery").innerHTML=""}function i(s){document.querySelector("#loader").classList.toggle("hidden",!s)}let d="",u=1;const f=15;document.getElementById("loader");const b=document.querySelector("#search-form"),g=document.querySelector("#load-more");document.querySelector(".gallery");let c=new Set,y=new w(".gallery a",{scrollZoom:!1});b.addEventListener("submit",async s=>{if(s.preventDefault(),d=document.querySelector("#search-input").value.trim(),!d){l.info({title:"Info",message:"Please enter a search query!"});return}q(),c.clear(),u=1,g.classList.add("hidden"),i(!0);try{const t=await m(d,u,f);if(i(!1),t.hits.length===0){l.warning({title:"Warning",message:"Nothing found! Try another search."});return}const a=t.hits.filter(e=>!c.has(e.id));a.forEach(e=>c.add(e.id)),h(a),y.refresh(),g.classList.remove("hidden")}catch(t){console.error("Error loading images:",t),i(!1),l.error({title:"Error",message:"Something went wrong. Please try again."})}});g.addEventListener("click",async()=>{u+=1,i(!0);try{const s=await m(d,u,f);i(!1);const t=s.hits.filter(a=>!c.has(a.id));t.forEach(a=>c.add(a.id)),h(t),y.refresh(),s.hits.length<f&&(g.classList.add("hidden"),l.warning({title:"Warning",message:"We're sorry, but you've reached the end of search results."}))}catch(s){console.error("Error loading more images:",s),i(!1),l.error({title:"Error",message:"Something went wrong. Please try again."})}});
//# sourceMappingURL=index.js.map
