import{a as L,S as v,i}from"./assets/vendor-851Qsuw-.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&r(a)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();const S="48211039-b5a5e94b0d08467a34362de56",b="https://pixabay.com/api/";async function h(s,e=1,n="",r="",t="all"){const o={key:S,q:s,image_type:t,orientation:"horizontal",safesearch:!0,per_page:15,page:e};n&&(o.category=n),r&&(o.colors=r);try{const a=await L.get(b,{params:o});return a.data.hits.length===0&&toastr.warning("No images found for your query. Try something else."),a.data}catch(a){throw toastr.error("Something went wrong. Please try again."),console.error(a),new Error("Failed to fetch images.")}}function y(s){const e=document.querySelector("#gallery"),n=s.map(r=>`
      <a href="${r.largeImageURL}" class="gallery-item">
        <img src="${r.webformatURL}" alt="${r.tags}" />
        <div class="info">
          <span><strong>Likes:</strong> ${r.likes}</span>
          <span><strong>Views:</strong> ${r.views}</span>
          <span><strong>Comments:</strong> ${r.comments}</span>
          <span><strong>Downloads:</strong> ${r.downloads}</span>
        </div>
      </a>
    `).join("");e.insertAdjacentHTML("beforeend",n),new SimpleLightbox(".gallery-item",{captionsData:"alt",captionDelay:250})}function E(){document.querySelector("#gallery").innerHTML=""}function q(){window.scrollBy({top:400,behavior:"smooth"})}let c="",d=1;const u=15,g=document.getElementById("loader"),I=document.querySelector("#search-form"),f=document.querySelector("#load-more");document.querySelector(".gallery");let l=new Set,p=new v(".gallery a",{scrollZoom:!1});document.addEventListener("touchstart",()=>{},{passive:!0});document.addEventListener("touchmove",()=>{},{passive:!0});function w(){g.innerHTML='<div class="spinner"></div>',g.style.display="block"}function m(){g.innerHTML="",g.style.display="none"}I.addEventListener("submit",async s=>{if(s.preventDefault(),c=document.querySelector("#search-input").value.trim(),!c){i.info({title:"Info",message:"Please enter a search query!"});return}E(),l.clear(),d=1,f.classList.add("hidden"),w();try{const e=await h(c,d,u);if(m(),e.hits.length===0){i.warning({title:"Warning",message:"Nothing found! Try another search."});return}const n=e.hits.filter(r=>!l.has(r.id));n.forEach(r=>l.add(r.id)),y(n),p.refresh(),e.hits.length>=u&&f.classList.remove("hidden")}catch(e){console.error("Error loading images:",e),m(),i.error({title:"Error",message:"Something went wrong. Please try again."})}});f.addEventListener("click",async()=>{d+=1,w();try{const s=await h(c,d,u);m();const e=s.hits.filter(n=>!l.has(n.id));e.forEach(n=>l.add(n.id)),e.length>0&&(y(e),p.refresh(),q()),s.hits.length<u&&(f.classList.add("hidden"),i.warning({title:"Warning",message:"We're sorry, but you've reached the end of search results."}))}catch(s){console.error("Error loading more images:",s),m(),i.error({title:"Error",message:"Something went wrong. Please try again."})}});
//# sourceMappingURL=index.js.map
